apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-client
  namespace: istio-httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-client
  template:
    metadata:
      labels:
        app: app-client
    spec:
      containers:
      - name: client
        image: curlimages/curl
        command: ["sh", "-c"]
        args:
        - |
          while true; do
            curl -H "Authorization: Bearer $TOKEN" http://httpbin.istio-httpbin.svc.cluster.local;
            sleep 10;
          done
        env:
        - name: TOKEN
          value: "eyJhbGciOiJSUzI1NiIsImtpZCI6IkRIRmJwb0lVYjV6cEdkSnRmOFhQUTJXX3Q5SVZOSS1jT3dzT2Z4SXlyUmsiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjQ2ODU5ODk3MDAsImZvbyI6ImJhciIsImlhdCI6MTUzMjM4OTcwMCwiaXNzIjoidGVzdGluZ0BzZWN1cmUuaXN0aW8uaW8iLCJzdWIiOiJ0ZXN0aW5nQHNlY3VyZS5pc3Rpby5pbyJ9.CfNnxWP2tcnR9q0vxyxweaF3ovQYHYZl82hAUsn21bwQd9zP7c-LS9qd_vpdLG4Tn1A15NxfCjp5f7QNBUo-KC9PJqYpgGjXG9JoDdJG9Now3RSwrzzD7BmEhS6B3u9ULJ7s7hRw3Mn5lE3u5DA3m2eFU8KvKcA5Q6Rp_mhJxV"