apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: auth-settings
  namespace: istio-httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.25/security/tools/jwt/samples/jwks.json"